//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchedMovies
    {
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string MovieGenre { get; set; }
        public string MovieDescription { get; set; }
        public string MovieRating { get; set; }
        public System.DateTime DateWatched { get; set; }
    }
}
